version: "3.9"

services:
  postgres:
    image: postgres:13.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./postgresdata:/var/lib/postgresql/data
      - ./migrations/dbinit.sql:/docker-entrypoint-initdb.d/dbinit.sql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-newPassword}
      POSTGRES_DB: ${POSTGRES_DB:-my-db-name}
    networks:
      - awesome

  backend:
    container_name: compose-back-container
    build:
      context: backend
      dockerfile: Dockerfile
    image: compose-back-optimal-image
    platform: linux/amd64
    networks:
      # - internal-network
      # - internet
      - awesome
    ports:
      - 4000:4000
    restart: unless-stopped
    env_file:
      - backend/.env
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads
      #- ./uploads:/usr/src/app/uploads

  frontend:
    container_name: compose-front-container
    build:
      context: frontend
      dockerfile: Dockerfile
    image: compose-front-optimal-image
    platform: linux/amd64
    networks:
      # - internet
      - awesome
    ports:
      - 8081:80
    restart: unless-stopped

networks:
  awesome:
    driver: bridge
