version: "3"

services:
  mongodb:
    image: mongo:6.0.1
    restart: always
    ports:
      - "27017:27017"
    networks:
      - awesome
    volumes:
      - dbdata6:/data/db

  my-app:
    depends_on:
      - mongodb
    image: cr.yandex/${REGISTRY_ID}/places:latest
    platform: linux/amd64
    build:
      context: .
    ports:
      - "${PORT:-3000}:3000"
    environment:
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - NODE_ENV=$NODE_ENV
      - PTH=$PTH
      - PORT=3000
      - CLIENT_ID=$CLIENT_ID
      - CLIENT_SECRET=$CLIENT_SECRET
      - DEV_JWT_SECRET=$DEV_JWT_SECRET
      - HOST=$HOST
    restart: always
    volumes:
      - .:/uploads
    networks:
      - awesome

networks:
  awesome:
    driver: bridge

volumes:
  dbdata6:
